{{- $namespace := include "common.namespace" . -}}

{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "graphql-engine" }}
  namespace: {{ $namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
{{  end  }}
